misc {
    force_default_wallpaper = -1
    disable_hyprland_logo = true
    font_family = JetBrains Mono Nerd
    splash_font_family = JetBrains Mono Nerd
    animate_manual_resizes = true
    animate_mouse_windowdragging = true
}
